### PR TITLE
Awesome-list integration

### PR DESCRIPTION
**Pull request by merdoyovski**
Several changes for awesome-list compatibility are applied
- Reworded long and some informal phrases
- Made main hyperlinks forward to GitHub repos, adding visual links for crates.
- Removed whitespace formatting done by prettier as it creates conflicts against awesome-lint
- Updated dead and wrong links. Removed duplicate ones.
- Updated contribution.md with awesome-lint suggestion.

This PR is a follow-up for the file changes mentioned in issue #22. After this is merged, the repository settings mentioned in the issue can be applied.
@uint

### CODE REVIEW

**Review by uint — COMMENTED** [review]
Awesome! I appreciate the more succinct phrasing, typo fixes, badges, and everything.

If we're switching to a different linter, would you mind deleting [.prettierrc.json](https://github.com/CosmWasm/cw-awesome/blob/master/.prettierrc.json) while we're here? It would be misleading now.

**Review by uint — APPROVED** [review]

**Comment by merdoyovski** [comment]
You're right. I deleted the old linter file and added the .yml config file for the automatic PR check.

**Comment by merdoyovski** [comment]
Re-requesting a review automatically removed @pyramation from reviewers and I don't have the authority to add him again. FYI.

**Review by uint — APPROVED** [review]
Cool, looks good!

**Pull request closed without merging**
