### PR TITLE
update README.md: Cosmwander and CWSimulate  to #tooling

### PR DESCRIPTION
**Pull request by MbBrainz**
Added 2 tools i think are great: 
Cosmwander and CWSimulate. They are actively maintained and developed. Repo(s) for cosmwander: https://github.com/muon-labs and for CWSimulate: https://github.com/Terran-One/cw-simulate-ui

### CODE REVIEW

**Comment by ethanfrey** [comment]
Nice addition.
Do you want to add those GitHub links as well to the PR (as is, just append `([GitHub Repo](...))` to the end or something like that?

**Comment by MbBrainz** [comment]
I just mentioned them so you could check the source code if you want. I tried to stick to the formatting I found in the readme and only include one link

**Comment by MbBrainz** [comment]
lets merge @ethanfrey :)

**Review by ethanfrey — APPROVED** [review]
Yes, both good ones. Sorry for the delay. I thought someone else was merging this repo.

**Comment by MbBrainz** [comment]
Done!

**Comment by MbBrainz** [comment]
Whoops, sorry my markdown extension updated the table of content on save, which applied more changes than intended. I removed those changes and now it should be correct: this merge request only adds the last 2 lines to section ## Tooling

**Comment by ethanfrey** [comment]
And I just merged #27 which also has CW-Simulate
Now we have it double.
I will merge and fix

**Comment by MbBrainz** [comment]
Oh damn... whoops, I guess it's a good sign. Everyone is just excited about it 😃

**Pull request merged**
